### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by Uwita082** [Picovoice/picovoice#433]
Hi, I am using a PsoC6 with a Rhino Speech-to-Intent context (EN). My problem is `$pv.Percent` and `$pv.TwoDigitInteger` return the number's literal rather than the number itself. My version of picovoice is `2.1.0.`

**Comment by laves** [comment]
@Uwita082, all slot values are strings because we don't want to influence the data type that the application has to use to store the number. Therefore, the number string should be parsed at the application level to the desired number type. The built-in slots simply convert something like `'twenty-five'` to `'25'` so that it can be parsed directly.

**Comment by Uwita082** [comment]
Yea, I get that it returns a string, of course. I was expecting that the parsed value would be '25' and not 'twenty five'. Or am I missing something here?

**Comment by laves** [comment]
Ah, okay, well that's not expected. We've just tried the built-ins here and can confirm that we're getting the correct number values. Are you seeing this when you test your context in Picovoice Console as well or does it just occur on PsoC6? If you feel comfortable sharing your context, we can see if there are any problems with the context itself.

**Comment by Uwita082** [comment]
Hi, it just occurs on PsoC6. 

My context is:
```
context:
  expressions:
    changeColor:
      - "@turn (all, the) lights (to) $color:color"
      - "@turn (the) [color, @lights] (to) $color:color"
    changeLightState:
      - "@switch $state:state (all, the) @lights"
      - "@switch (all, the) @lights $state:state"
    changeLightStateOff:
      - shut off (all, the) @lights
      - shut (all, the) @lights off
    changeBrightnessState:
      - "@dim (the, all) lights"
      - "@dim (the, all) @lights ($optionBrightness:option) $pv.Percent:percent"
      - "@turn (the) (@lights) @brightness ($optionBrightness:option)
        $stateBrightness:brightness"
      - "@turn (the) (@lights) @brightness $stateBrightness:brightness
        ($optionBrightness:option) $pv.Percent:percent"
      - "@turn (the) (@lights) @brightness ($optionBrightness:option)
        $pv.Percent:percent"
  slots:
    color:
      - blue
      - green
      - orange
      - pink
      - purple
      - red
      - white
      - yellow
    state:
      - off
      - on
    stateBrightness:
      - up
      - down
    optionBrightness:
      - to
      - by
      - at
  macros:
    lights:
      - lights
      - light
    turn:
      - turn
      - make
      - change
      - set
      - switch
    switch:
      - switch
      - turn
    dim:
      - dim
    brightness:
      - brightness
```
